CREATE TABLE Factura_Producto(
    ID_PRODUCTO VARCHAR2(255 BYTE) NOT NULL,
    CONSTRAINT FK_PRODUCTO_FACTURA FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO(CODIGO_BARRAS),
    ID_FACTURA NUMBER NOT NULL,
    CONSTRAINT FK_FACTURA_PRODUCTO FOREIGN KEY (ID_FACTURA)
    REFERENCES FACTURA(ID)
);

COMMIT;
